# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'roots.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_roots(object):
    def setupUi(self, roots):
        roots.setObjectName("roots")
        roots.resize(679, 476)
        self.IttTbl = QtWidgets.QTableWidget(roots)
        self.IttTbl.setGeometry(QtCore.QRect(10, 10, 471, 451))
        self.IttTbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.IttTbl.setAutoScroll(False)
        self.IttTbl.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.IttTbl.setRowCount(0)
        self.IttTbl.setObjectName("IttTbl")
        self.IttTbl.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.IttTbl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IttTbl.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IttTbl.setHorizontalHeaderItem(2, item)
        self.IttTbl.horizontalHeader().setVisible(True)
        self.IttTbl.horizontalHeader().setCascadingSectionResizes(False)
        self.IttTbl.horizontalHeader().setDefaultSectionSize(150)
        self.IttTbl.horizontalHeader().setStretchLastSection(True)
        self.IttTbl.verticalHeader().setVisible(False)

        self.retranslateUi(roots)
        QtCore.QMetaObject.connectSlotsByName(roots)

    def retranslateUi(self, roots):
        _translate = QtCore.QCoreApplication.translate
        roots.setWindowTitle(_translate("roots", "Roots"))
        item = self.IttTbl.horizontalHeaderItem(0)
        item.setText(_translate("roots", "Itteration #"))
        item = self.IttTbl.horizontalHeaderItem(1)
        item.setText(_translate("roots", "Approximate Root"))
        item = self.IttTbl.horizontalHeaderItem(2)
        item.setText(_translate("roots", "Precision"))
